version: 3

tasks:
  test:
    desc: run the tests
    cmds:
      - cmd: docker compose -f docker-compose-test.yml up --exit-code-from phpunit
  build:base-enums:
    desc: build the base enums from getCodeSets
    cmds:
      - cmd: php ./scripts/build-base-enums.php
  build:product-id-enum:
    desc: build the product id enum from getAllCubesListLite
    cmds:
      - cmd: php ./scripts/build-product-id-enum.php
  build:
    desc: build all of the enums
    cmds:
      - task: build:product-id-enum
      - task: build:base-enums
