<?php

namespace SeanJA\StatsCanAPI\ValueObjects\Enums;

enum GeographyEnum: int
{
    case ST_JOHNS_NEWFOUNDLAND_AND_LABRADOR = 2;
    case CHARLOTTETOWN_AND_SUMMERSIDE_PRINCE_EDWARD_ISLAND = 3;
    case HALIFAX_NOVA_SCOTIA = 4;
    case SAINT_JOHN_NEW_BRUNSWICK = 5;
    case QUBEC_QUEBEC = 6;
    case MONTRAL_QUEBEC = 7;
    case OTTAWAGATINEAU_ONTARIO_PART_ONTARIOQUEBEC = 8;
    case TORONTO_ONTARIO = 9;
    case THUNDER_BAY_ONTARIO = 10;
    case WINNIPEG_MANITOBA = 11;
    case REGINA_SASKATCHEWAN = 12;
    case SASKATOON_SASKATCHEWAN = 13;
    case EDMONTON_ALBERTA = 14;
    case CALGARY_ALBERTA = 15;
    case VANCOUVER_BRITISH_COLUMBIA = 16;
    case VICTORIA_BRITISH_COLUMBIA = 17;
    case WHITEHORSE_YUKON = 18;
    case YELLOWKNIFE_NORTHWEST_TERRITORIES = 19;
    case CANADA = 20;
}
