<?php

namespace SeanJA\StatsCanAPI\ValueObjects\Enums;
enum StatusCodeEnum: int
{
    case NORMAL = 0;
    case NOT_AVAILABLE_FOR_A_SPECIFIC_REFERENCE_PERIOD = 1;
    case LESS_THAN_THE_LIMIT_OF_DETECTION = 10;
    case VALUE_ROUNDED_TO_0_ZERO_WHERE_THERE_IS_A_MEANINGFUL_DISTINCTION_BETWEEN_TRUE_ZERO_AND_THE_VALUE_THAT_WAS_ROUNDED = 2;
    case DATA_QUALITY_EXCELLENT = 3;
    case DATA_QUALITY_VERY_GOOD = 4;
    case DATA_QUALITY_GOOD = 5;
    case DATA_QUALITY_ACCEPTABLE = 6;
    case USE_WITH_CAUTION = 7;
    case TOO_UNRELIABLE_TO_BE_PUBLISHED = 8;
    case NOT_APPLICABLE = 9;
}