<?php

namespace SeanJA\StatsCanAPI\ValueObjects\Enums;
enum WDSResponseStatusCodeEnum: int
{
    case CUBE_IS_CURRENTLY_BEING_PUBLISHED_PLEASE_TRY_AGAIN_LATER_ = 6;
    case CUBE_IS_NOT_AVAILABLE_FOR_MORE_INFORMATION_CONTACT_USTOLL_FREE_1_800_263_1136_514_283_8300_STATCAN_INFOSTATS_INFOSTATS_STATCANCANADA_CA_ = 7;
    case CUBE_PRODUCT_ID_IS_INVALID = 5;
    case INVALID_CUBE_AND_SERIES_COMBINATION = 2;
    case INVALID_DATE = 1;
    case INVALID_NUMBER_OF_REFERENCE_PERIODS = 8;
    case REQUEST_FAILED = 3;
    case SUCCESS = 0;
    case VECTOR_IS_INVALID = 4;
}
