<?php
namespace SeanJA\StatsCanAPI\ValueObjects\Enums;
enum WDSResponseStatusCodeEnum:int {
case SUCCESS = 0;
case INVALID_DATE = 1;
case INVALID_CUBE_AND_SERIES_COMBINATION = 2;
case REQUEST_FAILED = 3;
case VECTOR_IS_INVALID = 4;
case CUBE_PRODUCT_ID_IS_INVALID = 5;
case CUBE_IS_CURRENTLY_BEING_PUBLISHED_PLEASE_TRY_AGAIN_LATER = 6;
case CUBE_IS_NOT_AVAILABLE_FOR_MORE_INFORMATION_CONTACT_USTOLLFREE_18002631136___5142838300_STATCANINFOSTATSINFOSTATSSTATCANCANADACA = 7;
case INVALID_NUMBER_OF_REFERENCE_PERIODS = 8;
 } 